### ISSUE TITLE
[LAS-5] feat: 게시물 상세 페이지 퍼블리싱

### ISSUE THREAD

**Issue by Bsfla** [Sinchone/LastOne-FrontEnd#55]
## 🔨 설명

게시물 상세 페이지 퍼블리싱

### 페이지 경로 설정
- [x] 페이지 경로 설정 => /post/[id]
- [x] /post 접근 시 / 경로로 리다이렉트 설정

### 퍼블리싱
- [x] 헤더
- [x] 컨텐츠
  - [x] 글쓴이 정보
  - [x] 운동 날짜 및 선호 성별
  - [x] 헬스장 위치
  - [x] 상세 설명
- [x] 푸터 버튼(채팅하기 + 신청하기)
  - [x] 채팅하기 클릭: alert 로 구현 예정입니다. 문구 띄우기
  - [x] 신청하기 클릭: 모달 띄우기
  - [x] 파트너 신청 완료 후, 신청하기 버튼 -> 취소하기 버튼 변화
- [x] 모달
  - [x] 파트너 신청 완료 모달 
    - [x] 신청목록 확인 버튼 클릭: alert 로 문구 띄우기
    - [x] 나중에 다시 확인 버튼 클릭: 모달 닫기
  - [x] 파트너 매칭신청 취소 모달
    - [x] 취소하기 버튼 클릭: 취소 완료 svg와 문구 띄우기
    - [x] 아니오 버튼 클릭: 모달 닫기

**Comment by HalamLee** [comment]
현재 페이지 퍼블리싱을 완료했으나 2가지 문제점이 있습니다.

1. 모달이 열렸을 때의 카카오맵이 모달보다 z-index가 높은 이슈
![image](https://github.com/Sinchone/LastOne-FrontEnd/assets/87893624/e6cc788d-d3fc-43ac-99aa-624191f1ace9)

2. 리팩토링 필요
컴포넌트로 분리해서 더 가독성이 좋게 할 수 있을 것 같아서 리팩토링이 반드시 필요합니다.
또한, 모달 크기는 같으나 그 안의 컨텐츠만 다르기 때문에 이부분도 리팩토링이 필요하다 생각합니다.

**Comment by HalamLee** [comment]
06/01 AM 12:30
카카오맵이 모달보다 z-index가 높던 이슈 해결했습니다.
![image](https://github.com/Sinchone/LastOne-FrontEnd/assets/87893624/fc501204-7f96-4add-a061-f43ff2ef4ff0)
